# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'globalSurgeryCalc.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_globalSurgeryCalc(object):
    def setupUi(self, globalSurgeryCalc):
        globalSurgeryCalc.setObjectName("globalSurgeryCalc")
        globalSurgeryCalc.resize(515, 298)
        globalSurgeryCalc.setMinimumSize(QtCore.QSize(515, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("date_add.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        globalSurgeryCalc.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(globalSurgeryCalc)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.root_vBoxLayout = QtWidgets.QVBoxLayout()
        self.root_vBoxLayout.setObjectName("root_vBoxLayout")
        self.surgery_horizontalLayout = QtWidgets.QHBoxLayout()
        self.surgery_horizontalLayout.setObjectName("surgery_horizontalLayout")
        self.surgDate_label = QtWidgets.QLabel(globalSurgeryCalc)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.surgDate_label.setFont(font)
        self.surgDate_label.setObjectName("surgDate_label")
        self.surgery_horizontalLayout.addWidget(self.surgDate_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.surgery_horizontalLayout.addItem(spacerItem)
        self.surg_dateEdit = QtWidgets.QDateEdit(globalSurgeryCalc)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.surg_dateEdit.setFont(font)
        self.surg_dateEdit.setCalendarPopup(True)
        self.surg_dateEdit.setDate(QtCore.QDate(2018, 1, 1))
        self.surg_dateEdit.setObjectName("surg_dateEdit")
        self.surgery_horizontalLayout.addWidget(self.surg_dateEdit)
        self.copySurgDate_pushButton = QtWidgets.QPushButton(globalSurgeryCalc)
        self.copySurgDate_pushButton.setObjectName("copySurgDate_pushButton")
        self.surgery_horizontalLayout.addWidget(self.copySurgDate_pushButton)
        self.root_vBoxLayout.addLayout(self.surgery_horizontalLayout)
        self.assumed_horizontalLayout = QtWidgets.QHBoxLayout()
        self.assumed_horizontalLayout.setObjectName("assumed_horizontalLayout")
        self.assumedDate_label = QtWidgets.QLabel(globalSurgeryCalc)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.assumedDate_label.setFont(font)
        self.assumedDate_label.setObjectName("assumedDate_label")
        self.assumed_horizontalLayout.addWidget(self.assumedDate_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.assumed_horizontalLayout.addItem(spacerItem1)
        self.ass_dateEdit = QtWidgets.QDateEdit(globalSurgeryCalc)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ass_dateEdit.setFont(font)
        self.ass_dateEdit.setCalendarPopup(True)
        self.ass_dateEdit.setDate(QtCore.QDate(2018, 1, 1))
        self.ass_dateEdit.setObjectName("ass_dateEdit")
        self.assumed_horizontalLayout.addWidget(self.ass_dateEdit)
        self.copyAssDate_pushButton = QtWidgets.QPushButton(globalSurgeryCalc)
        self.copyAssDate_pushButton.setObjectName("copyAssDate_pushButton")
        self.assumed_horizontalLayout.addWidget(self.copyAssDate_pushButton)
        self.root_vBoxLayout.addLayout(self.assumed_horizontalLayout)
        self.relinq_horizontalLayout = QtWidgets.QHBoxLayout()
        self.relinq_horizontalLayout.setObjectName("relinq_horizontalLayout")
        self.relinquishedDate_label = QtWidgets.QLabel(globalSurgeryCalc)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.relinquishedDate_label.setFont(font)
        self.relinquishedDate_label.setObjectName("relinquishedDate_label")
        self.relinq_horizontalLayout.addWidget(self.relinquishedDate_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.relinq_horizontalLayout.addItem(spacerItem2)
        self.rel_dateEdit = QtWidgets.QDateEdit(globalSurgeryCalc)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rel_dateEdit.setFont(font)
        self.rel_dateEdit.setCalendarPopup(True)
        self.rel_dateEdit.setDate(QtCore.QDate(2018, 1, 1))
        self.rel_dateEdit.setObjectName("rel_dateEdit")
        self.relinq_horizontalLayout.addWidget(self.rel_dateEdit)
        self.copyRelDate_pushButton = QtWidgets.QPushButton(globalSurgeryCalc)
        self.copyRelDate_pushButton.setObjectName("copyRelDate_pushButton")
        self.relinq_horizontalLayout.addWidget(self.copyRelDate_pushButton)
        self.root_vBoxLayout.addLayout(self.relinq_horizontalLayout)
        self.end_horizontalLayout = QtWidgets.QHBoxLayout()
        self.end_horizontalLayout.setObjectName("end_horizontalLayout")
        self.globalPeriodEnd_label = QtWidgets.QLabel(globalSurgeryCalc)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.globalPeriodEnd_label.setFont(font)
        self.globalPeriodEnd_label.setObjectName("globalPeriodEnd_label")
        self.end_horizontalLayout.addWidget(self.globalPeriodEnd_label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.end_horizontalLayout.addItem(spacerItem3)
        self.globalEndDate_dateEdit = QtWidgets.QDateEdit(globalSurgeryCalc)
        self.globalEndDate_dateEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.globalEndDate_dateEdit.setFont(font)
        self.globalEndDate_dateEdit.setReadOnly(True)
        self.globalEndDate_dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.globalEndDate_dateEdit.setCalendarPopup(False)
        self.globalEndDate_dateEdit.setObjectName("globalEndDate_dateEdit")
        self.end_horizontalLayout.addWidget(self.globalEndDate_dateEdit)
        self.copyEndGlobalDate_pushButton = QtWidgets.QPushButton(globalSurgeryCalc)
        self.copyEndGlobalDate_pushButton.setObjectName("copyEndGlobalDate_pushButton")
        self.end_horizontalLayout.addWidget(self.copyEndGlobalDate_pushButton)
        self.root_vBoxLayout.addLayout(self.end_horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bothMsgs_lineEdit = QtWidgets.QLineEdit(globalSurgeryCalc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bothMsgs_lineEdit.setFont(font)
        self.bothMsgs_lineEdit.setReadOnly(True)
        self.bothMsgs_lineEdit.setObjectName("bothMsgs_lineEdit")
        self.horizontalLayout_4.addWidget(self.bothMsgs_lineEdit)
        self.copyBothMsgs_pushButton = QtWidgets.QPushButton(globalSurgeryCalc)
        self.copyBothMsgs_pushButton.setObjectName("copyBothMsgs_pushButton")
        self.horizontalLayout_4.addWidget(self.copyBothMsgs_pushButton)
        self.root_vBoxLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.quit_pushButton = QtWidgets.QPushButton(globalSurgeryCalc)
        self.quit_pushButton.setObjectName("quit_pushButton")
        self.horizontalLayout_2.addWidget(self.quit_pushButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.root_vBoxLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.root_vBoxLayout)

        self.retranslateUi(globalSurgeryCalc)
        self.quit_pushButton.clicked.connect(globalSurgeryCalc.close)
        QtCore.QMetaObject.connectSlotsByName(globalSurgeryCalc)

    def retranslateUi(self, globalSurgeryCalc):
        _translate = QtCore.QCoreApplication.translate
        globalSurgeryCalc.setWindowTitle(_translate("globalSurgeryCalc", "Global Surgery Period Calculator"))
        self.surgDate_label.setText(_translate("globalSurgeryCalc", "Surgery Date:"))
        self.surg_dateEdit.setDisplayFormat(_translate("globalSurgeryCalc", "MM/dd/yyyy"))
        self.copySurgDate_pushButton.setText(_translate("globalSurgeryCalc", "Copy"))
        self.assumedDate_label.setText(_translate("globalSurgeryCalc", "Assumed Care Date:  "))
        self.ass_dateEdit.setDisplayFormat(_translate("globalSurgeryCalc", "MM/dd/yyyy"))
        self.copyAssDate_pushButton.setText(_translate("globalSurgeryCalc", "Copy"))
        self.relinquishedDate_label.setText(_translate("globalSurgeryCalc", "Relinquished Date:"))
        self.rel_dateEdit.setDisplayFormat(_translate("globalSurgeryCalc", "MM/dd/yyyy"))
        self.copyRelDate_pushButton.setText(_translate("globalSurgeryCalc", "Copy"))
        self.globalPeriodEnd_label.setText(_translate("globalSurgeryCalc", "End of Global Period Date:"))
        self.globalEndDate_dateEdit.setDisplayFormat(_translate("globalSurgeryCalc", "MM/dd/yyyy"))
        self.copyEndGlobalDate_pushButton.setText(_translate("globalSurgeryCalc", "Copy"))
        self.bothMsgs_lineEdit.setToolTip(_translate("globalSurgeryCalc", "<html><head/><body><p>This text should be copied &amp; pasted into Item 19 on the CMS claim form.</p><p>-Can bill from date patient was transferred even if patient not seen that first day.</p><p>-Date of service must be <span style=\" font-weight:600; font-style:italic;\">date of surgery</span></p><p>-Item 19 must contain date care assumed and date care relinquished</p><p>Note: <span style=\" font-weight:600;\">Some</span> Medicare contractors require number of post-op days in 24G (units).</p></body></html>"))
        self.bothMsgs_lineEdit.setText(_translate("globalSurgeryCalc", "Assumed: xx/xx/xxxx  Relinquished: xx/xx/xxxx Number of Days: XX"))
        self.copyBothMsgs_pushButton.setText(_translate("globalSurgeryCalc", "Copy"))
        self.quit_pushButton.setText(_translate("globalSurgeryCalc", "Quit"))
        self.quit_pushButton.setShortcut(_translate("globalSurgeryCalc", "Q"))

